// SPDX-License-Identifier: GPL-3.0-only
//
// CONTRACT WITH THE PHONE: this file re-parses, through the REAL ac_parse_set
// in ../src/c/alarm_calc.c, packed strings produced by the REAL packAlarmSet
// (the compiled src/pkjs/alarm_pack.js, generated by tsc from
// src/ts/alarm_pack.ts) -- not hardcoded literals. tests/run_c_tests.sh
// invokes packAlarmSet via node for each of the three cases below (using the
// exact same semantic slot inputs tests/alarm_pack.test.js asserts against)
// and passes the resulting strings in as argv[1..3]. That closes the wire
// format's contract in BOTH directions: a packer regression (e.g. pad2
// emitting a single-digit hour, or daysToDigits inverting the weekday order)
// changes what argv actually contains, and the assertions below -- which
// encode the same semantic inputs the node call used, not the packed string
// itself -- catch it exactly as a parser regression would be caught. A
// one-sided edit to either the packer or the parser fails this test; see
// run_c_tests.sh for the node invocation and tests/alarm_pack.test.js for the
// independently-maintained JS-side pin of the same semantics.
//
// Build/run: this binary now REQUIRES the three packed strings as argv, so it
// cannot usefully be run standalone with plain gcc -- use
// tests/run_c_tests.sh (wired into `npm run test:c` / `npm test`), which
// builds it exactly the way test_alarm_calc.c's/test_escalation.c's own
// header comments document and supplies the node-generated argv.
#include "alarm_calc.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv) {
  if (argc != 4) {
    fprintf(stderr,
        "usage: %s <packed-3-slot> <packed-8-slot> <packed-empty>\n"
        "(these three come from the REAL packAlarmSet via node -- run through\n"
        "tests/run_c_tests.sh, not directly)\n", argv[0]);
    return 2;
  }
  const char *packed3 = argv[1];
  const char *packed8 = argv[2];
  const char *packed_empty = argv[3];

  Alarm out[MAX_ALARMS];
  int n;

  // packed3 came from the REAL packAlarmSet fed:
  //   [{enabled:true,time:'07:00',days:D('1111100')},
  //    {enabled:false,time:'08:30',days:D('0000011')},
  //    {enabled:true,time:'05:15',days:D('0000000')}]
  // (the exact case tests/alarm_pack.test.js's 'packs enabled and disabled
  // slots' / 'round-trips through unpackAlarmSet' assert on independently).
  n = ac_parse_set(packed3, out, MAX_ALARMS);
  assert(n == 3);
  assert(out[0].minute_of_day == 7 * 60);
  assert(out[0].weekday_mask == 0x1F);      // Mon-Fri, bit0=Mon .. bit4=Fri
  assert(out[0].enabled == true);
  assert(out[1].minute_of_day == 8 * 60 + 30);
  assert(out[1].weekday_mask == 0x60);      // Sat+Sun, bit5+bit6
  assert(out[1].enabled == false);
  assert(out[2].minute_of_day == 5 * 60 + 15);
  assert(out[2].weekday_mask == 0);         // one-time
  assert(out[2].enabled == true);
  printf("3-slot (from the real packer) OK: %s\n", packed3);

  // packed8 came from the REAL packAlarmSet fed exactly SLOT_COUNT (8) slots,
  // alternating enabled/disabled and weekday/one-time -- the same case
  // tests/alarm_pack.test.js's 'round-trips all SLOT_COUNT (8) slots by
  // content' asserts on independently.
  n = ac_parse_set(packed8, out, MAX_ALARMS);
  assert(n == MAX_ALARMS);
  for (int i = 0; i < MAX_ALARMS; i++) {
    assert(out[i].minute_of_day == i * 60);
    assert(out[i].enabled == (i % 2 == 0));
    assert(out[i].weekday_mask == (i % 2 == 0 ? 0x1F : 0));
  }
  printf("8-slot (from the real packer) OK: %s\n", packed8);

  // packed_empty came from the REAL packAlarmSet([]) -- must be "" (the
  // watch reads an empty AlarmSet as "no alarms").
  assert(strlen(packed_empty) == 0);
  n = ac_parse_set(packed_empty, out, MAX_ALARMS);
  assert(n == 0);
  printf("empty-set (from the real packer) OK\n");

  printf("ALL PACK/PARSE CONTRACT CASES PASSED (fed from the real compiled packer)\n");
  return 0;
}
